recipes:
  iron_sword:
    id: "iron_sword"
    profession: "BLACKSMITH_WEAPON"
    minLevel: 5
    workstation: "FORGE"
    inputs:
      - item: "iron_ingot"
        amount: 2
      - item: "wood_plank"
        amount: 1
    output:
      item: "iron_sword"
      amount: 1
    xp: 25

  leather_armor:
    id: "leather_armor"
    profession: "LEATHERWORKER"
    minLevel: 3
    workstation: "TANNERY"
    inputs:
      - item: "tanned_leather"
        amount: 4
    output:
      item: "leather_armor"
      amount: 1
    xp: 20
