resources:
  oak_log:
    id: "oak_log"
    blockId: "block_oak_log"
    profession: "LUMBERJACK"
    minLevel: 1
    xp: 10
    respawnSeconds: 60
  iron_ore:
    id: "iron_ore"
    blockId: "block_iron_ore"
    profession: "MINER"
    minLevel: 5
    xp: 20
    respawnSeconds: 120
  wheat_crop:
    id: "wheat_crop"
    blockId: "block_wheat"
    profession: "FARMER"
    minLevel: 1
    xp: 8
    respawnSeconds: 90
