waypoints:
  village_center:
    id: "village_center"
    name: "Centre du village"
    world: "overworld"
    x: 100
    y: 65
    z: 200

  tower_entrance:
    id: "tower_entrance"
    name: "Entrée de la tour"
    world: "overworld"
    x: 150
    y: 80
    z: 250

  ruins_entrance:
    id: "ruins_entrance"
    name: "Entrée des ruines"
    world: "overworld"
    x: 300
    y: 70
    z: 400

  guardian_room:
    id: "guardian_room"
    name: "Salle du gardien"
    world: "overworld"
    x: 320
    y: 75
    z: 420
